version: '3.8'
services:
  cv:
    build: .
    container_name: cv
    restart: unless-stopped
    expose:
      - "3020"
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true